app:
  name: "notifier"

network:
  host: "0.0.0.0"
  port: "8081"

logger:
  json_enable: false
  level: "debug"
  report: false

postgres:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "12345"
  db: "rutube"